name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
    
permissions:
  id-token: write
  contents: read
  
jobs:  

  build-deploy:
    runs-on: ubuntu-latest
    #container: node:16
    steps:
      # Step 1
    - name: Checkout to repo
      uses: actions/checkout@v2
      
      # Step build
    - name: build   
      run: |
         npm i
         cd client 
         npm i 
         npm run build
        # cd ..
        # node server.js
      
      # Step test
    - name: test
      run: |
         cd client
         npm i @testing-library/react
         npm i enzyme
         npm i @apollo/client@3.4.16
         npm i enzyme-adapter-react-16
         npm i history
         npm install jest@24.9.0
         npm run test
    
      # Step 2
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

      # Step 3
    - name: Create CodeDeploy Deployment
      id: deploy
      run: |
        aws deploy create-deployment \
        --application-name chatapp \
        --deployment-group-name chatapp-CD \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
